name: Create Codespace on PR
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  create_codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Create Codespace
        env:
          GH_TOKEN: ${{ secrets.MY_CUSTOM_TOKEN }}
        run: |
          gh codespace create --repo ${{ github.repository }} --branch ${{ github.head_ref }} --machine standardLinux32gb
