name: Create Codespace on PR
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  create_codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Create Codespace
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.codespaces.createWithRepoForAuthenticatedUser({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.ref,
              machine: 'm3.large'
            });
